=== Geoinformatics/GISON/cv04/spravne XSD/prezence.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="kurs" type="typ-kurs"/>
	
	<xs:complexType name="typ-kurs">
		<xs:sequence>
			<xs:element name="student" type="typ-student" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="nazev" type="xs:string" use="required"/>
		<xs:attribute name="datum" type="xs:date" use="required"/>
		<xs:attribute name="lektor" type="xs:string" use="required"/>
	</xs:complexType>

	<xs:complexType name="typ-student">
		<xs:attribute name="jmeno" type="xs:string" use="required"/>
		<xs:attribute name="prijmeni" type="xs:string" use="required"/>
	</xs:complexType>
</xs:schema>

=== Geoinformatics/GISON/Cvičení/cv04/spravne XSD/prezence1.xml
<?xml version="1.0" encoding="UTF-8"?>
<kurs nazev="xml" datum="2011-06-28" lektor="Petr KrulÃ­k" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="prezence.xsd">
	<student jmeno="Irena" prijmeni="Konfrstova"/>
	<student jmeno="Jozef" prijmeni="Kukucka"/>
	<!-- SK -->
	<student jmeno="Petra" prijmeni="Lecchiova"/>
	<student jmeno="Jiri" prijmeni="Matyasek"/>
	<student jmeno="Dana" prijmeni="Mrakotova"/>
	<student jmeno="Vilem" prijmeni="Pechanec"/>
	<student jmeno="Pavel" prijmeni="Perman"/>
	<student jmeno="Jiri" prijmeni="Sterba"/>
	<student jmeno="Pavel" prijmeni="Viktora"/>
</kurs>
